version: '3.7'

services:
  db:
    ports:
      - '27017:27017'
    container_name: api-mongo
    restart: always
    logging:
        options:
            max-size: 1g
    image: mongo
    env_file:
      - .env
    environment:
        MONGO_INITDB_USERNAME: ${DB_USERNAME}
        MONGO_INITDB_PASSWORD: ${DB_PASSWORD}
        MONGO_INITDB_DATABASE: ${DB_DATABASE}
    volumes:
      - mongo-data:/data/db 
  
  redis:
    container_name: cache
    image: "redis:6.2.6-alpine"
    command: redis-server --save 60 1 --requirepass redis123 --loglevel warning
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data


  server:
    container_name: web-api
    build:
      context: ./
      dockerfile: 'Dockerfile.dev'
    image: parallel-api
    command: npm run dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app    
volumes:
  mongo-data:
  redis-data: